### PR TITLE
Open xDrip on click/tap on widget

### PR DESCRIPTION
**Pull request by AdrianLxM**
A tap/click on the widget now opens or switches to the xDrip App (Home),

### CODE REVIEW

**Comment by StephenBlackWasAlreadyTaken** [comment]
Cool thanks!! Mind pointing this pr at https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental (its kind of our 'dev' branch)

**Comment by AdrianLxM** [comment]
Of course, sorry!
I've read https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/issues/1, but I'm still not sure which branch? Master?
Unfortunately I cannot test on the experimental branch in the next couple of days/weeks as my hardware is limited and my laptop does not allow for proper emulation of android.

**Comment by StephenBlackWasAlreadyTaken** [comment]
No worries, it looks straight forward and I will test it out (it will also
then be in the next beta), but yeah, pointing at master in there would be
great!

**Comment by StephenBlackWasAlreadyTaken** [comment]
Closing as this is now in the experimental repo, thanks again @AdrianLxM

**Pull request closed without merging**
